name: prerelease

on:
  push:
    branches:
      - next

jobs:
  prepublish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize the repository
        uses: ./.github/actions/repo-init
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build

      - name: Bump versions and publish packages
        run: |
          npx lerna publish --canary --preid $GITHUB_REF_NAME --dist-tag $GITHUB_REF_NAME --yes

      # - uses: actions/delete-package-versions@v2
      #   with:
      #     package-name: "test-core"
      #     min-versions-to-keep: 4

      # - uses: actions/delete-package-versions@v2
      #   with:
      #     package-name: "test-client"
      #     min-versions-to-keep: 4
