name: repo-init
description: Prepares the repository
inputs:
  token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: "https://registry.npmjs.org/"
        cache: "yarn"

    - name: Setup .npmrc
      shell: bash
      run: |
        npm set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    - name: Ensure access
      shell: bash
      run: npm whoami --registry https://registry.npmjs.org/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    - name: Config git user
      shell: bash
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
